/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "translation": {
        "common": {
            "success": string;
            "error": string;
            "notFound": string;
            "unauthorized": string;
            "forbidden": string;
            "badRequest": string;
            "internalError": string;
            "conflict": string;
            "tooManyRequests": string;
        };
        "auth": {
            "loginSuccess": string;
            "logoutSuccess": string;
            "registrationSuccess": string;
            "invalidCredentials": string;
            "emailAlreadyExists": string;
            "passwordResetSent": string;
            "passwordResetSuccess": string;
            "tokenExpired": string;
            "tokenInvalid": string;
            "accountNotVerified": string;
            "accountSuspended": string;
            "invalidResetToken": string;
        };
        "validation": {
            "emailInvalid": string;
            "passwordTooShort": string;
            "passwordTooWeak": string;
            "required": string;
            "minLength": string;
            "maxLength": string;
            "isEmail": string;
            "isString": string;
            "isNumber": string;
            "isBoolean": string;
            "isEnum": string;
            "min": string;
            "max": string;
            "isLatitude": string;
            "isLongitude": string;
            "isPhoneNumber": string;
            "isUrl": string;
            "isDate": string;
            "isArray": string;
            "arrayMinSize": string;
            "arrayMaxSize": string;
        };
        "otp": {
            "sent": string;
            "verified": string;
            "invalid": string;
            "expired": string;
            "locked": string;
            "cooldown": string;
            "alreadyVerified": string;
        };
        "user": {
            "profileUpdated": string;
            "roleChanged": string;
            "notFound": string;
            "suspended": string;
            "cannotChangeOwnRole": string;
        };
        "field": {
            "created": string;
            "updated": string;
            "deleted": string;
            "retrieved": string;
            "listRetrieved": string;
            "searchCompleted": string;
            "notFound": string;
            "notOwner": string;
            "invalidCoordinates": string;
            "updateFailed": string;
            "imageUploaded": string;
            "imageDeleted": string;
            "invalidFileType": string;
            "fileTooLarge": string;
            "maxImagesReached": string;
            "imageNotFound": string;
            "noFileProvided": string;
        };
        "timeSlot": {
            "created": string;
            "updated": string;
            "deleted": string;
            "retrieved": string;
            "listRetrieved": string;
            "bulkCreated": string;
            "notFound": string;
            "startTimeBeforeEndTime": string;
            "overlappingSlot": string;
            "overlappingSlotDetails": string;
            "alreadyBooked": string;
            "notAvailable": string;
            "cannotModifyBooked": string;
            "invalidDateRange": string;
            "invalidDaysOfWeek": string;
            "noDatesGenerated": string;
        };
        "booking": {
            "created": string;
            "confirmed": string;
            "cancelled": string;
            "checkedIn": string;
            "completed": string;
            "notFound": string;
            "alreadyBooked": string;
            "paymentPending": string;
            "paymentFailed": string;
            "cannotCancel": string;
            "paymentDeadlineExpired": string;
            "invalidStatus": string;
        };
        "payment": {
            "initiated": string;
            "success": string;
            "failed": string;
            "refunded": string;
            "insufficientBalance": string;
            "invalidGateway": string;
        };
        "wallet": {
            "credited": string;
            "debited": string;
            "insufficientBalance": string;
            "withdrawalSuccess": string;
            "withdrawalFailed": string;
        };
        "notification": {
            "deviceRegistered": string;
            "deviceUnregistered": string;
            "bookingConfirmed": {
                "title": string;
                "body": string;
            };
            "bookingReminder": {
                "title": string;
                "body": string;
            };
            "bookingCancelled": {
                "title": string;
                "body": string;
            };
            "newBooking": {
                "title": string;
                "body": string;
            };
            "noShow": {
                "title": string;
                "body": string;
                "warningOneMore": string;
                "suspended": string;
            };
            "paymentSuccess": {
                "title": string;
                "body": string;
            };
            "refundProcessed": {
                "title": string;
                "body": string;
            };
        };
        "review": {
            "created": string;
            "updated": string;
            "deleted": string;
            "retrieved": string;
            "listRetrieved": string;
            "replyAdded": string;
            "notFound": string;
            "alreadyExists": string;
            "bookingNotCompleted": string;
            "notOwner": string;
        };
        "errors": {
            "BOOKING_NOT_FOUND": string;
            "BOOKING_NOT_COMPLETED": string;
            "REVIEW_ALREADY_EXISTS": string;
            "REVIEW_NOT_FOUND": string;
            "FORBIDDEN": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
